name: leo
description: A set of general utilities for the server
version: 1.0.4+4
homepage: 'https://github.com/therenca/leo'

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  colorize: ^3.0.0
  postgres: ^2.4.3
  http: ^0.13.4
  intl: ^0.17.0