name: leo
description: A set of general utilities for the server
version: 1.0.5+3
homepage: 'https://github.com/therenca/leo'

environment:
  sdk: '>=3.6.0 <= 3.7.0'

dependencies:
  colorize: ^3.0.0
  postgres: ^2.4.3
  http: ^1.3.0
  intl: ^0.19.0
  mime: ^1.0.2
  collection: ^1.16.0