name: leo
description: A set of general utilities for the server
version: 1.0.4+1
author: Therenca Mureithi <therencamureithi@gmail.com>
homepage: 'https://github.com/therenca/leo'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  colorize: ^2.0.0
  postgres: ^2.1.1
  uuid: ^3.0.0
  http: ^0.13.0
  intl: ^0.17.0
