name: leo
description: A set of general utilities for the server
version: 0.0.1
author: Therenca Mureithi
homepage: therencamureithi@gmail.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  colorize: any
  postgres: ^2.1.1
  uuid: ^2.2.2
